# Generated by Django 6.0.2 on 2026-05-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0002_locker_created_at_locker_is_active_locker_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='locker',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='locker',
            name='rental_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='locker',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='locker',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use')], default='Available', max_length=20),
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
