# Generated by Django 6.0.2 on 2026-05-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0003_remove_userprofile_user_alter_locker_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locker',
            options={'ordering': ['locker_number']},
        ),
        migrations.RenameField(
            model_name='locker',
            old_name='number',
            new_name='locker_number',
        ),
        migrations.RenameField(
            model_name='locker',
            old_name='rental_duration',
            new_name='rental_hours',
        ),
        migrations.RenameField(
            model_name='locker',
            old_name='owner',
            new_name='rented_by',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='time_left',
        ),
        migrations.AlterField(
            model_name='locker',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied')], default='Available', max_length=20),
        ),
    ]
